const students = [{
    "id": 1,
    "first_name": "Arlin",
    "last_name": "Wilkowski",
    "elamil": "awilkowski0@furl.net"
}, {
    "id": 2,
    "first_name": "Isaak",
    "last_name": "Tilt",
    "elamil": "itilt1@barnesandnoble.com"
}, {
    "id": 3,
    "first_name": "Caprice",
    "last_name": "Ortas",
    "elamil": "cortas2@narod.ru"
}, {
    "id": 4,
    "first_name": "Elisha",
    "last_name": "McCarlich",
    "elamil": "emccarlich3@tuttocitta.it"
}, {
    "id": 5,
    "first_name": "Delly",
    "last_name": "Flawith",
    "elamil": "dflawith4@java.com"
}, {
    "id": 6,
    "first_name": "Glennis",
    "last_name": "Horstead",
    "elamil": "ghorstead5@dyndns.org"
}, {
    "id": 7,
    "first_name": "Verne",
    "last_name": "Germann",
    "elamil": "vgermann6@webs.com"
}, {
    "id": 8,
    "first_name": "Lorrie",
    "last_name": "Philipps",
    "elamil": "lphilipps7@yandex.ru"
}, {
    "id": 9,
    "first_name": "Lewes",
    "last_name": "Vinas",
    "elamil": "lvinas8@exblog.jp"
}, {
    "id": 10,
    "first_name": "Reta",
    "last_name": "Bamlett",
    "elamil": "rbamlett9@about.com"
}]

module.exports = students;